---
- hosts: web
  vars:
    source_path: '{{ source_path }}'
    deploy_path: /srv/question-service/front
  tasks:
    - name: Ensure frontend directory exists
      sudo: yes
      file: path={{ deploy_path }}
            state=directory
            owner={{ ansible_ssh_user }}

    - name: Build
      local_action: command npm run build
      args:
        chdir: "{{ source_path }}"

    - name: Deploy
      copy: src={{ item }} 
            dest={{ deploy_path }} 
            owner={{ ansible_ssh_user }}
      with_fileglob:
        - "{{ source_path}}/dist/*"
